apiVersion: v1
kind: Service
metadata:
  name: sentinel-backend
  namespace: sentinel-backend
  labels:
    app: sentinel-backend
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  selector:
    app: sentinel-backend
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
