apiVersion: v1
kind: Service
metadata:
  name: sentinel-gateway-proxy
  namespace: sentinel-gateway
  labels:
    app: sentinel-gateway-proxy
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  selector:
    app: sentinel-gateway-proxy
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
